name: Deploy Landing to Server

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout репозитория
    - name: Checkout code
      uses: actions/checkout@v4

    # Установка Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22' # Укажите вашу версию Node.js

    # Установка зависимостей
    - name: Install dependencies
      run: yarn

    # Сборка Next.js приложения
    - name: Build Next.js app
      run: yarn build

    # Передача собранных файлов на сервер
    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        # Установка SSH-ключа
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

        # Передача файлов на сервер
        scp -r .next $SERVER_USER@$SERVER_IP:/var/www/nextjs-app/.next
        scp -r public $SERVER_USER@$SERVER_IP:/var/www/nextjs-app/public
        scp package.json $SERVER_USER@$SERVER_IP:/var/www/nextjs-app/
        scp package-lock.json $SERVER_USER@$SERVER_IP:/var/www/nextjs-app/

        # Выполнение команд на сервере
        ssh $SERVER_USER@$SERVER_IP << 'EOF'
          cd /var/www/nextjs-app
          yarn
          pm2 restart nextjs-app || pm2 start npm --name "nextjs-app" -- start -- -p 3000
        EOF
